/**
 * GENERATED by `aegis ontology generate` — do not edit by hand.
 *
 * Source: ontology/aegis.yaml and the modules it composes (Article XI).
 * Regenerate with `aegis ontology generate`; CI fails on drift.
 */

export const ONTOLOGY_VERSION = "1.4.0" as const;
export const ONTOLOGY_NAMESPACE = "aegis.lk" as const;

/** Ordered low to high — the index is the clearance level (spec 03). */
export const HANDLING_CODES = ["open", "restricted", "sensitive"] as const;
export const SOURCE_TYPES = ["algorithmic", "commission_report", "court_record", "government_system", "human", "investigator", "open_source", "sensor"] as const;

export const MODULES = {
  "criminal_network": { version: "1.1.0", namespace: "aegis.lk/criminal-network", enabled: true },
  "platform": { version: "1.2.0", namespace: "aegis.lk/platform", enabled: true },
} as const;

export const OBJECT_TYPES = {
  "location": { label: "Location", implements: [], module: "criminal_network" },
  "organization": { label: "Organization", implements: ["party"], module: "criminal_network" },
  "person": { label: "Person", implements: ["identifiable", "party"], module: "criminal_network" },
  "phone_number": { label: "Phone number", implements: ["identifiable"], module: "criminal_network" },
  "vehicle": { label: "Vehicle", implements: [], module: "criminal_network" },
} as const;

export const INTERFACES = {
  "identifiable": { label: "Identifiable", implementors: ["person", "phone_number"], module: "platform" },
  "party": { label: "Party", implementors: ["person", "organization"], module: "platform" },
} as const;

export const CATEGORIES = {
  "financial": { label: "Financial/enterprise", color: "#00897b" },
  "ideological": { label: "Ideological", color: "#7c4dff" },
  "kinship": { label: "Kinship/personal", color: "#6d4c41" },
  "prison_co_location": { label: "Prison co-location", color: "#ef6c00" },
  "transnational": { label: "Transnational", color: "#3949ab" },
} as const;

/**
 * Interface endpoints are expanded to concrete object types, because that
 * is what a claim records (spec 08 §4); `subjectInterfaces` keeps what was
 * declared, for a UI that wants to say `party` rather than list members.
 */
export const PREDICATES = {
  "affiliated_with": { subject: ["person"], object: ["organization"], allowsLiteral: true, category: "ideological", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "allied_with": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "assessed_as_criminal_organization": { subject: ["organization"], object: "literal", allowsLiteral: true, category: "ideological", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "born_on": { subject: ["person"], object: "literal", allowsLiteral: true, category: null, symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "close_associate_of": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "co_arrested_with": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "transnational", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "co_attacker_with": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "ideological", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "co_located_in_prison_with": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "prison_co_location", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "communicated_with": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "transnational", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "conspired_against": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "conspired_with": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "ideological", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "financed_and_supplied_materiel_to": { subject: ["person"], object: ["organization"], allowsLiteral: false, category: "financial", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "foreign_contact_of": { subject: ["person"], object: ["organization"], allowsLiteral: false, category: "transnational", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "founded": { subject: ["person"], object: ["organization"], allowsLiteral: false, category: "ideological", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "has_nic": { subject: ["person"], object: "literal", allowsLiteral: true, category: null, symmetric: false, identifier: true, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "helped_establish_operations_of": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "transnational", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "killed_family_of": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "known_as": { subject: ["organization", "person"], object: "literal", allowsLiteral: true, category: null, symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "masterminded_attack_with": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "ideological", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "member_of": { subject: ["person"], object: ["organization"], allowsLiteral: false, category: "ideological", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "ordered_killing_of": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "partnered_with": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "pledged_allegiance_to": { subject: ["organization", "person"], object: ["organization"], allowsLiteral: false, category: "ideological", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "provided_military_training_to": { subject: ["person"], object: ["organization", "person"], allowsLiteral: false, category: "ideological", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "reachable_on": { subject: ["phone_number"], object: "literal", allowsLiteral: true, category: null, symmetric: false, identifier: true, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "registered_as": { subject: ["vehicle"], object: "literal", allowsLiteral: true, category: null, symmetric: false, identifier: true, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "rival_of": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "sibling_of": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "kinship", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "splinter_affiliate_of": { subject: ["organization"], object: ["organization"], allowsLiteral: false, category: "ideological", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "spouse_of": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "kinship", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "successor_leader_of": { subject: ["person"], object: ["organization"], allowsLiteral: false, category: "ideological", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "tipped_off_police_on": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: false, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "trafficked_narcotics_with": { subject: ["person"], object: ["person"], allowsLiteral: false, category: "transnational", symmetric: true, identifier: false, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
} as const;

export type HandlingCode = (typeof HANDLING_CODES)[number];
export type SourceType = (typeof SOURCE_TYPES)[number];
export type ObjectTypeName = keyof typeof OBJECT_TYPES;
export type InterfaceName = keyof typeof INTERFACES;
export type CategoryName = keyof typeof CATEGORIES;
export type PredicateName = keyof typeof PREDICATES;
