/**
 * GENERATED by `aegis ontology generate` — do not edit by hand.
 *
 * Source: ontology/aegis.yaml and the modules it composes (Article XI).
 * Regenerate with `aegis ontology generate`; CI fails on drift.
 */

export const ONTOLOGY_VERSION = "2.0.0" as const;
export const ONTOLOGY_NAMESPACE = "aegis.lk" as const;

/** Ordered low to high — the index is the clearance level (spec 03). */
export const HANDLING_CODES = ["open", "restricted", "sensitive"] as const;
export const SOURCE_TYPES = ["algorithmic", "commission_report", "court_record", "government_system", "human", "investigator", "open_source", "sensor"] as const;

export const MODULES = {
  "criminal_network": { version: "2.0.0", namespace: "aegis.lk/criminal-network", enabled: true },
  "platform": { version: "1.4.0", namespace: "aegis.lk/platform", enabled: true },
} as const;

/**
 * The object-view descriptor (spec 09 §6.2). `display` names the properties a
 * heading is drawn from; `properties` carries what a generic renderer needs to
 * draw a value honestly — its label, whether it may repeat, whether it is
 * clearance-gated, and whether conflicting values are preserved rather than
 * overwritten.
 */
export const OBJECT_TYPES = {
  "arrest": { label: "Arrest", implements: ["event"], module: "criminal_network", display: { title: "summary", subtitle: null }, properties: { "notes": { label: "Notes", type: "text", required: false, many: false, sensitivity: null, conflicts: null, shared: "notes" }, "summary": { label: "Summary", type: "text", required: false, many: false, sensitivity: null, conflicts: null, shared: "summary" } } },
  "location": { label: "Location", implements: ["place"], module: "criminal_network", display: { title: "name", subtitle: null }, properties: { "geometry": { label: "Geometry", type: "geo", required: false, many: false, sensitivity: null, conflicts: null, shared: "geometry" }, "name": { label: "Name", type: "text", required: true, many: false, sensitivity: null, conflicts: null, shared: null }, "notes": { label: "Notes", type: "text", required: false, many: false, sensitivity: null, conflicts: null, shared: "notes" } } },
  "meeting": { label: "Meeting", implements: ["event"], module: "criminal_network", display: { title: "summary", subtitle: null }, properties: { "notes": { label: "Notes", type: "text", required: false, many: false, sensitivity: null, conflicts: null, shared: "notes" }, "summary": { label: "Summary", type: "text", required: false, many: false, sensitivity: null, conflicts: null, shared: "summary" } } },
  "observation": { label: "Observation", implements: ["event"], module: "criminal_network", display: { title: "summary", subtitle: null }, properties: { "notes": { label: "Notes", type: "text", required: false, many: false, sensitivity: null, conflicts: null, shared: "notes" }, "summary": { label: "Summary", type: "text", required: false, many: false, sensitivity: null, conflicts: null, shared: "summary" } } },
  "organization": { label: "Organization", implements: ["party"], module: "criminal_network", display: { title: "name", subtitle: "aliases" }, properties: { "aliases": { label: "Aliases", type: "text", required: false, many: true, sensitivity: null, conflicts: null, shared: "alias" }, "name": { label: "Name", type: "text", required: true, many: false, sensitivity: null, conflicts: null, shared: null }, "notes": { label: "Notes", type: "text", required: false, many: false, sensitivity: null, conflicts: null, shared: "notes" } } },
  "person": { label: "Person", implements: ["identifiable", "party"], module: "criminal_network", display: { title: "name", subtitle: "aliases" }, properties: { "aliases": { label: "Aliases", type: "text", required: false, many: true, sensitivity: null, conflicts: null, shared: "alias" }, "date_of_birth": { label: "Date of birth", type: "date", required: false, many: false, sensitivity: null, conflicts: "preserve", shared: null }, "name": { label: "Name", type: "text", required: true, many: false, sensitivity: null, conflicts: null, shared: null }, "nic": { label: "NIC", type: "identifier", required: false, many: false, sensitivity: "restricted", conflicts: null, shared: "registered_identifier" }, "notes": { label: "Notes", type: "text", required: false, many: false, sensitivity: null, conflicts: null, shared: "notes" } } },
  "phone_number": { label: "Phone number", implements: ["identifiable"], module: "criminal_network", display: { title: "number", subtitle: null }, properties: { "number": { label: "Number", type: "identifier", required: true, many: false, sensitivity: "restricted", conflicts: null, shared: "registered_identifier" } } },
  "travel": { label: "Travel", implements: ["event"], module: "criminal_network", display: { title: "summary", subtitle: null }, properties: { "notes": { label: "Notes", type: "text", required: false, many: false, sensitivity: null, conflicts: null, shared: "notes" }, "summary": { label: "Summary", type: "text", required: false, many: false, sensitivity: null, conflicts: null, shared: "summary" } } },
  "vehicle": { label: "Vehicle", implements: [], module: "criminal_network", display: { title: "description", subtitle: "registration" }, properties: { "description": { label: "Description", type: "text", required: true, many: false, sensitivity: null, conflicts: null, shared: null }, "registration": { label: "Registration", type: "identifier", required: false, many: false, sensitivity: null, conflicts: null, shared: null } } },
} as const;

export const INTERFACES = {
  "event": { label: "Event", implementors: ["meeting", "arrest", "travel", "observation"], module: "platform" },
  "identifiable": { label: "Identifiable", implementors: ["person", "phone_number"], module: "platform" },
  "party": { label: "Party", implementors: ["person", "organization"], module: "platform" },
  "place": { label: "Place", implementors: ["location"], module: "platform" },
} as const;

export const CATEGORIES = {
  "financial": { label: "Financial/enterprise", color: "#00897b" },
  "geospatial": { label: "Geospatial", color: "#2e7d32" },
  "ideological": { label: "Ideological", color: "#7c4dff" },
  "kinship": { label: "Kinship/personal", color: "#6d4c41" },
  "occurrence": { label: "Occurrence", color: "#455a64" },
  "prison_co_location": { label: "Prison co-location", color: "#ef6c00" },
  "transnational": { label: "Transnational", color: "#3949ab" },
} as const;

/**
 * Interface endpoints are expanded to concrete object types, because that
 * is what a claim records (spec 08 §4); `subjectInterfaces` keeps what was
 * declared, for a UI that wants to say `party` rather than list members.
 */
export const PREDICATES = {
  "affiliated_with": { label: "Affiliated with", subject: ["person"], object: ["organization"], allowsLiteral: true, category: "ideological", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "allied_with": { label: "Allied with", subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "assessed_as_criminal_organization": { label: "Assessed as criminal organization", subject: ["organization"], object: "literal", allowsLiteral: true, category: "ideological", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "born_on": { label: "Born on", subject: ["person"], object: "literal", allowsLiteral: true, category: null, symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "close_associate_of": { label: "Close associate of", subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "co_arrested_with": { label: "Co arrested with", subject: ["person"], object: ["person"], allowsLiteral: false, category: "transnational", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "co_attacker_with": { label: "Co attacker with", subject: ["person"], object: ["person"], allowsLiteral: false, category: "ideological", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "co_located_in_prison_with": { label: "Co located in prison with", subject: ["person"], object: ["person"], allowsLiteral: false, category: "prison_co_location", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "communicated_with": { label: "Communicated with", subject: ["person"], object: ["person"], allowsLiteral: false, category: "transnational", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "conspired_against": { label: "Conspired against", subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "conspired_with": { label: "Conspired with", subject: ["person"], object: ["person"], allowsLiteral: false, category: "ideological", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "controls": { label: "Controls", subject: ["organization", "person"], object: ["organization"], allowsLiteral: false, category: "financial", symmetric: false, identifier: false, property: null, subjectInterfaces: ["party"], objectInterfaces: [], module: "criminal_network" },
  "financed_and_supplied_materiel_to": { label: "Financed and supplied materiel to", subject: ["person"], object: ["organization"], allowsLiteral: false, category: "financial", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "foreign_contact_of": { label: "Foreign contact of", subject: ["person"], object: ["organization"], allowsLiteral: false, category: "transnational", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "founded": { label: "Founded", subject: ["person"], object: ["organization"], allowsLiteral: false, category: "ideological", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "has_arrestee": { label: "Arrestee", subject: ["arrest"], object: ["person"], allowsLiteral: false, category: "occurrence", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "has_arresting_officer": { label: "Arresting officer", subject: ["arrest"], object: ["organization", "person"], allowsLiteral: false, category: "occurrence", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: ["party"], module: "criminal_network" },
  "has_attendee": { label: "Attendee", subject: ["meeting", "observation"], object: ["organization", "person"], allowsLiteral: false, category: "occurrence", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: ["party"], module: "criminal_network" },
  "has_geometry": { label: "Geometry", subject: ["location"], object: "literal", allowsLiteral: true, category: "geospatial", symmetric: false, identifier: false, property: "geometry", subjectInterfaces: ["place"], objectInterfaces: [], module: "criminal_network" },
  "has_nic": { label: "Has NIC", subject: ["person"], object: "literal", allowsLiteral: true, category: null, symmetric: false, identifier: true, property: "nic", subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "has_observer": { label: "Observer", subject: ["observation"], object: ["organization", "person"], allowsLiteral: false, category: "occurrence", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: ["party"], module: "criminal_network" },
  "has_participant": { label: "Participant", subject: ["arrest", "meeting", "observation", "travel"], object: ["organization", "person"], allowsLiteral: false, category: "occurrence", symmetric: false, identifier: false, property: null, subjectInterfaces: ["event"], objectInterfaces: ["party"], module: "criminal_network" },
  "has_traveller": { label: "Traveller", subject: ["travel"], object: ["person"], allowsLiteral: false, category: "occurrence", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "helped_establish_operations_of": { label: "Helped establish operations of", subject: ["person"], object: ["person"], allowsLiteral: false, category: "transnational", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "killed_family_of": { label: "Killed family of", subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "known_as": { label: "Known as", subject: ["organization", "person"], object: "literal", allowsLiteral: true, category: null, symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "masterminded_attack_with": { label: "Masterminded attack with", subject: ["person"], object: ["person"], allowsLiteral: false, category: "ideological", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "member_of": { label: "Member of", subject: ["person"], object: ["organization"], allowsLiteral: false, category: "ideological", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "ordered_killing_of": { label: "Ordered killing of", subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "partnered_with": { label: "Partnered with", subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "pledged_allegiance_to": { label: "Pledged allegiance to", subject: ["organization", "person"], object: ["organization"], allowsLiteral: false, category: "ideological", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "provided_military_training_to": { label: "Provided military training to", subject: ["person"], object: ["organization", "person"], allowsLiteral: false, category: "ideological", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "reachable_on": { label: "Reachable on", subject: ["phone_number"], object: "literal", allowsLiteral: true, category: null, symmetric: false, identifier: true, property: "number", subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "registered_as": { label: "Registered as", subject: ["vehicle"], object: "literal", allowsLiteral: true, category: null, symmetric: false, identifier: true, property: "registration", subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "rival_of": { label: "Rival of", subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "sibling_of": { label: "Sibling of", subject: ["person"], object: ["person"], allowsLiteral: false, category: "kinship", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "splinter_affiliate_of": { label: "Splinter affiliate of", subject: ["organization"], object: ["organization"], allowsLiteral: false, category: "ideological", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "spouse_of": { label: "Spouse of", subject: ["person"], object: ["person"], allowsLiteral: false, category: "kinship", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "successor_leader_of": { label: "Successor leader of", subject: ["person"], object: ["organization"], allowsLiteral: false, category: "ideological", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "summarized_as": { label: "Summary", subject: ["arrest", "meeting", "observation", "travel"], object: "literal", allowsLiteral: true, category: "occurrence", symmetric: false, identifier: false, property: "summary", subjectInterfaces: ["event"], objectInterfaces: [], module: "criminal_network" },
  "tipped_off_police_on": { label: "Tipped off police on", subject: ["person"], object: ["person"], allowsLiteral: false, category: "financial", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "took_place_at": { label: "Took place at", subject: ["arrest", "meeting", "observation"], object: ["location"], allowsLiteral: false, category: "geospatial", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: ["place"], module: "criminal_network" },
  "trafficked_narcotics_with": { label: "Trafficked narcotics with", subject: ["person"], object: ["person"], allowsLiteral: false, category: "transnational", symmetric: true, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: [], module: "criminal_network" },
  "travelled_from": { label: "Departed from", subject: ["travel"], object: ["location"], allowsLiteral: false, category: "geospatial", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: ["place"], module: "criminal_network" },
  "travelled_to": { label: "Arrived at", subject: ["travel"], object: ["location"], allowsLiteral: false, category: "geospatial", symmetric: false, identifier: false, property: null, subjectInterfaces: [], objectInterfaces: ["place"], module: "criminal_network" },
} as const;

export type HandlingCode = (typeof HANDLING_CODES)[number];
export type SourceType = (typeof SOURCE_TYPES)[number];
export type ObjectTypeName = keyof typeof OBJECT_TYPES;
export type InterfaceName = keyof typeof INTERFACES;
export type CategoryName = keyof typeof CATEGORIES;
export type PredicateName = keyof typeof PREDICATES;

/**
 * Geospatial vocabularies (spec 10 §4.2). Code-owned rather than declared,
 * because the validator and the renderer must implement every value — but
 * exported here so no geospatial vocabulary is typed into React either.
 *
 * `GEO_ADMIN_LEVELS` is ordered coarse to fine; `not_administrative` is not
 * a rung on it, which is why it is listed apart: asking whether it is
 * coarser than a locality has no answer.
 */
export const GEO_ADMIN_LEVELS = ["country", "subdivision", "locality", "site"] as const;
export const GEO_NOT_ADMINISTRATIVE = "not_administrative" as const;
export const GEO_DERIVATIONS = ["address_match", "admin_unit_boundary", "admin_unit_centroid", "analyst_estimate", "coverage_area", "instrument_fix", "source_stated_coordinates"] as const;
export type GeoAdminLevel =
  | (typeof GEO_ADMIN_LEVELS)[number]
  | typeof GEO_NOT_ADMINISTRATIVE;
export type GeoDerivation = (typeof GEO_DERIVATIONS)[number];
