"""Persistence adapter: SQLAlchemy models and engine."""

from aegis.store.engine import Base, get_engine, get_sessionmaker
from aegis.store.models import (
    AuditLog,
    AuthzOutbox,
    CaseFile,
    CaseMember,
    CaseReference,
    Claim,
    ClaimRelation,
    CustodyEvent,
    Derivative,
    EdgeProjection,
    Entity,
    EntityCanonicalMap,
    ErCandidate,
    EvidenceItem,
    Hypothesis,
    HypothesisClaim,
    HypothesisRevision,
    IdentityDecision,
    IdentityMembership,
    IdentityNegativeConstraint,
    IdentityRevision,
    InvestigationTask,
    Mention,
    ReviewQueue,
    Source,
    SourceRecord,
)

__all__ = [
    "AuditLog",
    "AuthzOutbox",
    "Base",
    "CaseFile",
    "CaseMember",
    "CaseReference",
    "Claim",
    "ClaimRelation",
    "CustodyEvent",
    "Derivative",
    "EdgeProjection",
    "Entity",
    "EntityCanonicalMap",
    "ErCandidate",
    "EvidenceItem",
    "Hypothesis",
    "HypothesisClaim",
    "HypothesisRevision",
    "IdentityDecision",
    "IdentityMembership",
    "IdentityNegativeConstraint",
    "IdentityRevision",
    "InvestigationTask",
    "Mention",
    "ReviewQueue",
    "Source",
    "SourceRecord",
    "get_engine",
    "get_sessionmaker",
]
