#!/usr/bin/env bash
# Aegis dev bootstrap (speckit T1). Idempotent — safe to re-run.
# Requires: services up (`make up`), docker, curl, python3.
#   1. MinIO buckets (raw-landing, evidence, exports) + versioning
#   2. Keycloak realm check (imported automatically at container start)
#   3. OpenFGA store "aegis" + authorization model push
#   4. Writes FGA_STORE_ID / FGA_MODEL_ID to infra/.runtime.env (gitignored)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENVFILE_ARGS=()
[ -f "$ROOT/.env" ] && ENVFILE_ARGS=(--env-file "$ROOT/.env")
COMPOSE=(docker compose "${ENVFILE_ARGS[@]}" -f "$ROOT/infra/docker-compose.yml")

FGA_URL="${FGA_API_URL:-http://localhost:8082}"
KC_URL="${KEYCLOAK_URL:-http://localhost:8180}"
KC_REALM="${KEYCLOAK_REALM:-aegis}"

step() { printf '\n==> %s\n' "$*"; }

step "postgres: reachable?"
"${COMPOSE[@]}" exec -T postgres pg_isready -U "${POSTGRES_USER:-aegis}" -d "${POSTGRES_DB:-aegis}"

step "minio: create buckets (raw-landing, evidence, exports)"
"${COMPOSE[@]}" --profile tools run --rm minio-init

step "keycloak: verify realm '$KC_REALM' (imported at container start)"
if curl -fsS "$KC_URL/realms/$KC_REALM/.well-known/openid-configuration" >/dev/null; then
  echo "keycloak realm '$KC_REALM': OK ($KC_URL)"
else
  echo "ERROR: realm '$KC_REALM' not found at $KC_URL — check 'docker compose logs keycloak'" >&2
  exit 1
fi

step "openfga: ensure store 'aegis'"
store_id="$(curl -fsS "$FGA_URL/stores" | python3 -c '
import json, sys
stores = json.load(sys.stdin).get("stores", [])
print(next((s["id"] for s in stores if s["name"] == "aegis"), ""))
')"
if [ -z "$store_id" ]; then
  store_id="$(curl -fsS -X POST "$FGA_URL/stores" \
    -H 'content-type: application/json' -d '{"name":"aegis"}' \
    | python3 -c 'import json,sys; print(json.load(sys.stdin)["id"])')"
  echo "created store: $store_id"
else
  echo "store exists: $store_id"
fi

step "openfga: write authorization model (infra/fga/model.json)"
model_id="$(curl -fsS -X POST "$FGA_URL/stores/$store_id/authorization-models" \
  -H 'content-type: application/json' \
  --data-binary @"$ROOT/infra/fga/model.json" \
  | python3 -c 'import json,sys; print(json.load(sys.stdin)["authorization_model_id"])')"
echo "model written: $model_id"

step "write infra/.runtime.env"
cat > "$ROOT/infra/.runtime.env" <<EOF
# Generated by infra/bootstrap.sh — do not commit (gitignored).
FGA_STORE_ID=$store_id
FGA_MODEL_ID=$model_id
EOF
echo "wrote $ROOT/infra/.runtime.env"

step "bootstrap complete"
cat <<EOF
  postgres   localhost:5433  db=${POSTGRES_DB:-aegis} (openfga db alongside)
  minio      http://localhost:9001 (console)  buckets: raw-landing, evidence, exports
  keycloak   $KC_URL  realm=$KC_REALM  users: dev-analyst/analyst, dev-auditor/auditor, dev-admin/admin
  openfga    $FGA_URL  store=$store_id
EOF
