"""Legacy migration tests (speckit T8).

Unit layer: the verb-remap table is exercised as a pure function over the
committed legacy graph JSON.  Integration layer (PostgreSQL): the full
migration must reconcile — 41 entities, every edge → ≥1 claim per the remap
table — and a re-run must change nothing.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from aegis.audit import verify
from aegis.evidence import LocalFilesystemVault
from aegis.migration import (
    CONFIDENCE_TAG_GRADING,
    VERB_REMAP,
    LegacyMigrationError,
    migrate,
    remap_edge,
    validate_legacy_maps,
)
from aegis.ontology import load
from aegis.store import (
    Claim,
    Entity,
    IdentityMembership,
    Mention,
    Source,
    SourceRecord,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
# The immutable committed legacy graph (57 edges). NOT output/real_graph.json —
# that file is regenerated by `aegis projections rebuild` into the *remapped*
# projection (63 edges), so reading it here would couple the test to whether a
# rebuild has run.
BASELINE = REPO_ROOT / "tests" / "snapshots" / "real_graph.baseline.json"


@pytest.fixture(scope="module")
def ontology():
    return load(REPO_ROOT / "ontology" / "aegis.yaml")


@pytest.fixture(scope="module")
def baseline_graph() -> dict:
    return json.loads(BASELINE.read_text(encoding="utf-8"))


# ── unit: the remap table as a pure function ────────────────────────────────


def test_legacy_maps_validate_against_ontology(ontology) -> None:
    validate_legacy_maps(ontology)


def test_every_committed_edge_remaps(ontology, baseline_graph) -> None:
    """Migration AC: each edge → ≥1 claim; splits per the documented table."""
    total = 0
    for edge in baseline_graph["edges"]:
        drafts = remap_edge(edge, ontology)
        assert len(drafts) >= 1
        total += len(drafts)
    expected_splits = sum(
        1
        for edge in baseline_graph["edges"]
        if len(VERB_REMAP.get(edge["relation"], (None,))) > 1
    )
    assert total == len(baseline_graph["edges"]) + expected_splits


def test_compound_verbs_split_into_two_claims(ontology) -> None:
    edge = {
        "relation": "sibling_co_attacker_of",
        "confidence": "EXTRACTED",
        "layer": "IDEOLOGICAL",
        "start_date": None,
        "end_date": None,
        "location": None,
    }
    predicates = [d["predicate"] for d in remap_edge(edge, ontology)]
    assert predicates == ["sibling_of", "co_attacker_with"]
    assert all(d["split"] for d in remap_edge(edge, ontology))


def test_former_ally_splits_the_time_window(ontology) -> None:
    edge = {
        "relation": "former_ally_turned_rival_of",
        "confidence": "INFERRED",
        "layer": "FINANCIAL",
        "start_date": "2002-01-01",
        "end_date": None,
        "location": None,
    }
    allied, rival = remap_edge(edge, ontology)
    assert allied["predicate"] == "allied_with"
    assert (allied["valid_from"], allied["valid_to"]) == (None, "2002-01-01")
    assert rival["predicate"] == "rival_of"
    assert (rival["valid_from"], rival["valid_to"]) == ("2002-01-01", None)


def test_suspected_prefix_becomes_credibility_cap(ontology) -> None:
    edge = {
        "relation": "suspected_successor_leader_of",
        "confidence": "AMBIGUOUS",
        "layer": "IDEOLOGICAL",
        "start_date": None,
        "end_date": None,
        "location": None,
    }
    (draft,) = remap_edge(edge, ontology)
    assert draft["predicate"] == "successor_leader_of"
    assert draft["credibility_capped"] is True
    # AMBIGUOUS maps to 'doubtful', already weaker than the 'possibly_true' cap.
    assert draft["credibility_normalized"] == "doubtful"
    # An EXTRACTED "suspected" edge would be capped down to possibly_true.
    edge["confidence"] = "EXTRACTED"
    (capped,) = remap_edge(edge, ontology)
    assert capped["credibility_normalized"] == "possibly_true"


def test_location_moves_onto_the_claim(ontology) -> None:
    dubai = {
        "relation": "helped_establish_in_dubai",
        "confidence": "INFERRED",
        "layer": "TRANSNATIONAL",
        "start_date": None,
        "end_date": None,
        "location": "Dubai, UAE",
    }
    (draft,) = remap_edge(dubai, ontology)
    assert draft["predicate"] == "helped_establish_operations_of"
    # the edge's own location wins over the remap default
    assert draft["location_text"] == "Dubai, UAE"
    tamil = {
        "relation": "ran_narcotics_from_tamil_nadu_with",
        "confidence": "INFERRED",
        "layer": "TRANSNATIONAL",
        "start_date": None,
        "end_date": None,
        "location": None,
    }
    (draft,) = remap_edge(tamil, ontology)
    assert draft["predicate"] == "trafficked_narcotics_with"
    assert draft["location_text"] == "Tamil Nadu route"


def test_unknown_verb_fails_with_precise_error(ontology) -> None:
    edge = {
        "relation": "definitely_not_a_verb",
        "confidence": "EXTRACTED",
        "layer": "FINANCIAL",
    }
    with pytest.raises(LegacyMigrationError, match="predicates.definitely_not_a_verb"):
        remap_edge(edge, ontology)


def test_unknown_confidence_tag_fails(ontology) -> None:
    edge = {"relation": "member_of", "confidence": "GUESSED", "layer": "IDEOLOGICAL"}
    with pytest.raises(LegacyMigrationError, match="confidence.GUESSED"):
        remap_edge(edge, ontology)


def test_undeclared_category_correction_fails(ontology) -> None:
    # member_of is ideological; a FINANCIAL legacy layer is not a declared correction.
    edge = {"relation": "member_of", "confidence": "EXTRACTED", "layer": "FINANCIAL"}
    with pytest.raises(LegacyMigrationError, match="predicates.member_of.category"):
        remap_edge(edge, ontology)


def test_confidence_tag_map_matches_spec() -> None:
    assert CONFIDENCE_TAG_GRADING == {
        "EXTRACTED": ("confirmed", "record_confirmed"),
        "INFERRED": ("probably_true", "partially_corroborated"),
        "AMBIGUOUS": ("doubtful", "unverified"),
    }


# ── integration: full migration against PostgreSQL ──────────────────────────


@pytest.fixture(scope="module")
def migration_engine() -> sa.Engine:
    database_url = os.getenv("AEGIS_TEST_DATABASE_URL")
    if not database_url:
        pytest.skip("set AEGIS_TEST_DATABASE_URL to run PostgreSQL migration tests")
    config = Config(str(REPO_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(REPO_ROOT / "migrations"))
    previous = os.environ.get("AEGIS_DATABASE_URL")
    os.environ["AEGIS_DATABASE_URL"] = database_url
    from aegis.config import get_settings

    get_settings.cache_clear()
    command.upgrade(config, "head")
    engine = sa.create_engine(database_url)
    # The migration uses deterministic ids, so start from clean domain tables
    # (audit_log stays — it is append-only and the chain must remain valid).
    with engine.begin() as connection:
        connection.execute(
            sa.text(
                "TRUNCATE claim_relation, review_queue, claim, identity_membership, "
                "mention, evidence_item, custody_event, derivative, source_record, "
                "source, case_member, case_file, entity, authz_outbox CASCADE"
            )
        )
    yield engine
    engine.dispose()
    if previous is None:
        os.environ.pop("AEGIS_DATABASE_URL", None)
    else:
        os.environ["AEGIS_DATABASE_URL"] = previous
    get_settings.cache_clear()


@pytest.fixture(scope="module")
def migrated(migration_engine: sa.Engine, tmp_path_factory: pytest.TempPathFactory):
    vault = LocalFilesystemVault(tmp_path_factory.mktemp("vault"))
    with Session(migration_engine) as session:
        first = migrate(session, vault=vault)
    with Session(migration_engine) as session:
        second = migrate(session, vault=vault)
    return {"engine": migration_engine, "first": first, "second": second}


@pytest.mark.integration
def test_migration_counts_reconcile(migrated, baseline_graph) -> None:
    first = migrated["first"]
    assert first.entities_created == 41 == len(baseline_graph["nodes"])
    assert first.sources_created == len(baseline_graph["meta"]["sources"]) == 12
    assert first.records_created == 12
    assert first.mentions == 41
    assert first.edges_total == len(baseline_graph["edges"]) == 57
    # every edge produced ≥1 claim, splits included, all listed in the report
    assert len(first.remap_log) == 57
    assert all(len(entry["predicates"]) >= 1 for entry in first.remap_log)
    expected_split_claims = sum(len(e["predicates"]) for e in first.remap_log)
    assert first.edge_claims_created == expected_split_claims == 63
    report = first.to_dict()
    assert len(report["splits"]) == 6
    assert len(report["credibility_caps"]) == 2
    assert len(report["category_corrections"]) == 7


@pytest.mark.integration
def test_migration_is_idempotent(migrated) -> None:
    second = migrated["second"]
    assert second.entities_created == 0
    assert second.sources_created == 0
    assert second.records_created == 0
    assert second.node_claims_created == 0
    assert second.edge_claims_created == 0
    first = migrated["first"]
    assert second.entities_existing == first.entities_created
    assert second.edge_claims_existing == first.edge_claims_created
    assert second.node_claims_existing == first.node_claims_created


@pytest.mark.integration
def test_migrated_store_contents(migrated, baseline_graph) -> None:
    engine = migrated["engine"]
    with Session(engine) as session:
        assert session.scalar(select(func.count()).select_from(Entity)) == 41
        assert session.scalar(select(func.count()).select_from(Source)) == 12
        assert session.scalar(select(func.count()).select_from(SourceRecord)) == 12
        assert session.scalar(select(func.count()).select_from(Mention)) == 41
        assert (
            session.scalar(
                select(func.count())
                .select_from(IdentityMembership)
                .where(IdentityMembership.decided_by == "rule:legacy-slug")
            )
            == 41
        )
        # one content-addressed snapshot backs every record (same bytes → one hash)
        hashes = set(session.scalars(select(SourceRecord.content_hash)))
        assert len(hashes) == 1

        # affiliation fallback: NTJ resolves to the organization entity,
        # unmatched affiliation strings stay as literals
        ntj = session.scalar(
            select(Entity).where(Entity.label == "National Thowheeth Jamaath")
        )
        assert ntj is not None and ntj.entity_type == "organization"
        resolved = session.scalar(
            select(func.count())
            .select_from(Claim)
            .where(Claim.predicate == "affiliated_with", Claim.object_id == ntj.entity_id)
        )
        assert resolved >= 15  # the extremism network members
        literal_affiliations = set(
            session.scalars(
                select(Claim.object_value).where(
                    Claim.predicate == "affiliated_with", Claim.object_id.is_(None)
                )
            )
        )
        assert "Madush drug network" in literal_affiliations
        assert "LTTE (alleged)" in literal_affiliations

        # grading preserved: original tag + scheme on every edge claim
        schemes = set(
            session.scalars(
                select(Claim.credibility_scheme).where(
                    Claim.credibility_scheme.isnot(None)
                )
            )
        )
        assert schemes == {"legacy-confidence-tag"}

        # the former-ally regime change produced complementary windows
        allied = session.scalar(
            select(Claim).where(
                Claim.predicate == "allied_with", Claim.excerpt.like("%Moratu Saman%")
            )
        )
        rival = session.scalar(
            select(Claim).where(
                Claim.predicate == "rival_of", Claim.excerpt.like("%Moratu Saman%")
            )
        )
        assert allied is not None and rival is not None
        assert allied.record_id == rival.record_id

        # Article X: the audit chain over the whole run verifies
        report = verify(session)
        assert report.valid, report.reason
