"""Action request models generated from the ontology (spec 08 §6.1).

GENERATED by `aegis ontology generate` — do not edit by hand.

One model per declared action. ``extra='forbid'`` is the whole point:
a parameter the ontology does not declare is rejected here, so no
caller can reach a field the ontology never described.
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any

from pydantic import BaseModel, ConfigDict



class AdjudicateIdentityRequest(BaseModel):
    """Declared parameters of the `adjudicate_identity` action."""

    model_config = ConfigDict(extra="forbid")

    mode: str
    note: str
    parent_revision_id: int
    candidate_id: str | None = None
    entity_id: str | None = None
    evidence_basis: str | None = None
    mention_a: str | None = None
    mention_b: str | None = None
    mention_ids: list[str] | None = None
    protected_person: bool = False
    target_entity_id: str | None = None


class AssignCaseMemberRequest(BaseModel):
    """Declared parameters of the `assign_case_member` action."""

    model_config = ConfigDict(extra="forbid")

    case_id: str
    role: str
    user_id: str


class LinkClaimsRequest(BaseModel):
    """Declared parameters of the `link_claims` action."""

    model_config = ConfigDict(extra="forbid")

    from_claim: str
    relation: str
    to_claim: str


class OpenCaseRequest(BaseModel):
    """Declared parameters of the `open_case` action."""

    model_config = ConfigDict(extra="forbid")

    purpose: str
    title: str
    case_id: str | None = None
    handling_code: str = 'open'


class RecordClaimRequest(BaseModel):
    """Declared parameters of the `record_claim` action."""

    model_config = ConfigDict(extra="forbid")

    predicate: str
    record_id: str
    analytic_confidence: str | None = None
    assertion_type: str = 'reported'
    case_id: str | None = None
    claim_id: str | None = None
    collection_method: str | None = None
    credibility_normalized: str = 'cannot_judge'
    credibility_original: str | None = None
    credibility_scheme: str | None = None
    event_time_earliest: datetime | None = None
    event_time_latest: datetime | None = None
    excerpt: str | None = None
    handling_code: str = 'open'
    jurisdiction: str | None = None
    location_text: str | None = None
    object_entity_type: str | None = None
    object_id: str | None = None
    object_mention_id: str | None = None
    object_value: Any | None = None
    subject_entity_type: str | None = None
    subject_id: str | None = None
    subject_mention_id: str | None = None
    supersedes: str | None = None
    valid_from: date | None = None
    valid_to: date | None = None
    verification_status: str = 'unverified'


class RegisterEvidenceRequest(BaseModel):
    """Declared parameters of the `register_evidence` action."""

    model_config = ConfigDict(extra="forbid")

    description: str
    acquired_at: datetime | None = None
    acquired_by: str | None = None
    case_id: str | None = None
    content_hash: str | None = None
    evidence_id: str | None = None
    handling_code: str = 'restricted'
    legal_basis: str | None = None
    record_id: str | None = None
    storage_uri: str | None = None


class ReleaseQuarantineRequest(BaseModel):
    """Declared parameters of the `release_quarantine` action."""

    model_config = ConfigDict(extra="forbid")

    note: str
    record_id: str


class RemoveCaseMemberRequest(BaseModel):
    """Declared parameters of the `remove_case_member` action."""

    model_config = ConfigDict(extra="forbid")

    case_id: str
    user_id: str


class RetractClaimRequest(BaseModel):
    """Declared parameters of the `retract_claim` action."""

    model_config = ConfigDict(extra="forbid")

    claim_id: str
    reason: str


class ReviewSuggestionRequest(BaseModel):
    """Declared parameters of the `review_suggestion` action."""

    model_config = ConfigDict(extra="forbid")

    decision: str
    suggestion_id: str
    edits: dict[str, Any] | None = None
    note: str | None = None


class SealRecordRequest(BaseModel):
    """Declared parameters of the `seal_record` action."""

    model_config = ConfigDict(extra="forbid")

    reason: str
    resource_id: str


class SubmitSuggestionRequest(BaseModel):
    """Declared parameters of the `submit_suggestion` action."""

    model_config = ConfigDict(extra="forbid")

    payload: dict[str, Any]
    producer: str
    case_id: str | None = None
    expires_at: datetime | None = None
    idempotency_key: str | None = None
    producer_meta: dict[str, Any] | None = None
    producer_version: str = 'unversioned'
    record_id: str | None = None
    suggestion_id: str | None = None
    suggestion_kind: str = 'claim_draft'
    supersedes: str | None = None


class TransferCustodyRequest(BaseModel):
    """Declared parameters of the `transfer_custody` action."""

    model_config = ConfigDict(extra="forbid")

    evidence_id: str
    occurred_at: datetime
    purpose: str
    to_actor: str
    from_actor: str | None = None
    hash_checked: bool = False
    note: str | None = None


#: action name -> generated request model.
REQUEST_MODELS: dict[str, type[BaseModel]] = {
    "adjudicate_identity": AdjudicateIdentityRequest,
    "assign_case_member": AssignCaseMemberRequest,
    "link_claims": LinkClaimsRequest,
    "open_case": OpenCaseRequest,
    "record_claim": RecordClaimRequest,
    "register_evidence": RegisterEvidenceRequest,
    "release_quarantine": ReleaseQuarantineRequest,
    "remove_case_member": RemoveCaseMemberRequest,
    "retract_claim": RetractClaimRequest,
    "review_suggestion": ReviewSuggestionRequest,
    "seal_record": SealRecordRequest,
    "submit_suggestion": SubmitSuggestionRequest,
    "transfer_custody": TransferCustodyRequest,
}

__all__ = ['AdjudicateIdentityRequest', 'AssignCaseMemberRequest', 'LinkClaimsRequest', 'OpenCaseRequest', 'REQUEST_MODELS', 'RecordClaimRequest', 'RegisterEvidenceRequest', 'ReleaseQuarantineRequest', 'RemoveCaseMemberRequest', 'RetractClaimRequest', 'ReviewSuggestionRequest', 'SealRecordRequest', 'SubmitSuggestionRequest', 'TransferCustodyRequest']
