"""Generate the artifacts that derive from the ontology (spec 08 §8, ADR-038).

Spec 01 §5 listed three codegen targets as Phase 1 deliverables and none was
ever built (T29 found this; ADR-038 records it). Rather than restore them
wholesale, each target is built by the phase whose consumer needs it. This
module holds the Phase 3 targets:

============================  =========================================
Target                        Consumer
============================  =========================================
``ontology/history/composed-<version>.json``   the T35 compatibility diff
``ontology/release.json``                      the T35 CI gates
``ui/src/api/ontology.ts``                     the workspace (T37/T38)
============================  =========================================

Everything here is **deterministic**: sorted keys, LF line endings, no
timestamps. A generated file that changed because it was regenerated on a
Tuesday would make the CI drift gate worthless.

The composed artifact is the *declaration*, not the resolved registry —
interfaces unexpanded, `shared:` references intact (spec 08 §7.2). What the
diff must answer is "did the vocabulary change", and resolution is derived, so
including it would make an interface gaining an implementor look like every
predicate that targets it changed.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from hashlib import sha256
from pathlib import Path
from typing import Any

from aegis.ontology.loader import Ontology
from aegis.ontology.modules import Composition

#: Written into every generated file. The check is a substring match in tests,
#: so keep it stable.
DO_NOT_EDIT = "GENERATED by `aegis ontology generate` — do not edit by hand."


@dataclass
class GeneratedFile:
    path: Path
    content: str

    @property
    def drifted(self) -> bool:
        """True when what is on disk differs from what would be written."""
        if not self.path.exists():
            return True
        return self.path.read_text(encoding="utf-8") != self.content

    def write(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        # newline="\n" explicitly: the default on Windows is CRLF, which would
        # make every generated file drift the moment a Windows checkout ran the
        # generator.
        self.path.write_text(self.content, encoding="utf-8", newline="\n")


@dataclass
class GenerateReport:
    files: list[GeneratedFile] = field(default_factory=list)

    @property
    def drifted(self) -> list[GeneratedFile]:
        return [f for f in self.files if f.drifted]


def canonical_json(value: Any) -> str:
    """One serialization, everywhere: sorted keys, two-space indent, LF, UTF-8."""
    return json.dumps(value, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def content_hash(value: Any) -> str:
    return sha256(canonical_json(value).encode("utf-8")).hexdigest()


# ── the composed artifact (spec 08 §7.2) ────────────────────────────────────


def composed_artifact(composition: Composition, ontology: Ontology) -> dict[str, Any]:
    """The normalized composed registry — what a version bump is diffed against."""
    document = {
        key: value
        for key, value in composition.document.items()
        if key not in ("version", "namespace")
    }
    return {
        "version": ontology.version,
        "namespace": ontology.namespace,
        "modules": [
            {
                "name": info.name,
                "namespace": info.namespace,
                "version": info.version,
                "enabled": info.enabled,
                "imports": info.imports,
            }
            for _, info in sorted(composition.modules.items())
        ],
        "owners": dict(sorted(composition.owners.items())),
        "ontology": document,
    }


def release_metadata(
    artifact: dict[str, Any],
    *,
    release: dict[str, Any] | None,
    previous: dict[str, Any] | None,
) -> dict[str, Any]:
    """Metadata for the current version, chained to the previous one.

    The chain is what makes the T35 compatibility check a filesystem
    comparison rather than commit archaeology (H-16): ``previous_version``
    names the artifact to diff against, and ``previous_content_hash`` proves
    that artifact has not been edited since.

    ``proposal`` and ``compatibility`` are **authored**, not derived — they
    come from the manifest's optional ``release:`` block. T33 records them as
    ``null`` when absent; T35 makes CI reject that.
    """
    declared = release or {}
    metadata = {
        "version": artifact["version"],
        "content_hash": content_hash(artifact),
        "modules": {
            module["name"]: module["version"] for module in artifact["modules"]
        },
        "proposal": declared.get("proposal"),
        "compatibility": declared.get("compatibility"),
        "previous_version": None,
        "previous_content_hash": None,
    }
    if previous is not None and previous.get("version") != metadata["version"]:
        metadata["previous_version"] = previous.get("version")
        metadata["previous_content_hash"] = previous.get("content_hash")
    elif previous is not None:
        # Regenerating without a bump must not rewrite the chain, or running
        # the generator twice would erase where this version came from.
        metadata["previous_version"] = previous.get("previous_version")
        metadata["previous_content_hash"] = previous.get("previous_content_hash")
    return metadata


# ── the workspace constants (spec 08 §8) ────────────────────────────────────


def _ts_literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def typescript_constants(ontology: Ontology) -> str:
    """The ontology as TypeScript the workspace can import.

    Predicates and object types are the reason this exists: the runtime
    ``GET /v1/ontology/vocabulary`` route serves handling codes, source types
    and assertion types, and nothing else, so a client has no typed way to know
    a predicate exists. That is the gap T39's exit criterion measures.

    ``ONTOLOGY_VERSION`` travels with them so a bundle can notice it was built
    against a different ontology than the server is running.
    """
    lines: list[str] = [
        "/**",
        f" * {DO_NOT_EDIT}",
        " *",
        " * Source: ontology/aegis.yaml and the modules it composes (Article XI).",
        " * Regenerate with `aegis ontology generate`; CI fails on drift.",
        " */",
        "",
        f"export const ONTOLOGY_VERSION = {_ts_literal(ontology.version)} as const;",
        f"export const ONTOLOGY_NAMESPACE = {_ts_literal(ontology.namespace)} as const;",
        "",
        "/** Ordered low to high — the index is the clearance level (spec 03). */",
        f"export const HANDLING_CODES = {_ts_literal(list(ontology.handling_codes))} as const;",
        f"export const SOURCE_TYPES = {_ts_literal(sorted(ontology.source_types))} as const;",
        "",
        "export const MODULES = {",
    ]
    for name, info in sorted(ontology.modules.items()):
        lines.append(
            f"  {_ts_literal(name)}: {{ version: {_ts_literal(info.version)}, "
            f"namespace: {_ts_literal(info.namespace)}, "
            f"enabled: {'true' if info.enabled else 'false'} }},"
        )
    lines += ["} as const;", "", "export const OBJECT_TYPES = {"]
    for name, spec in sorted(ontology.object_types.items()):
        lines.append(
            f"  {_ts_literal(name)}: {{ label: {_ts_literal(spec.label)}, "
            f"implements: {_ts_literal(sorted(spec.implements))}, "
            f"module: {_ts_literal(ontology.owner_module(name))} }},"
        )
    lines += ["} as const;", "", "export const INTERFACES = {"]
    for name, spec in sorted(ontology.interfaces.items()):
        lines.append(
            f"  {_ts_literal(name)}: {{ label: {_ts_literal(spec.label or name)}, "
            f"implementors: {_ts_literal(ontology.implementors(name))}, "
            f"module: {_ts_literal(ontology.owner_module(name))} }},"
        )
    lines += ["} as const;", "", "export const CATEGORIES = {"]
    for name, spec in sorted(ontology.categories.items()):
        lines.append(
            f"  {_ts_literal(name)}: {{ label: {_ts_literal(spec.label or name)}, "
            f"color: {_ts_literal(spec.color)} }},"
        )
    lines += [
        "} as const;",
        "",
        "/**",
        " * Interface endpoints are expanded to concrete object types, because that",
        " * is what a claim records (spec 08 §4); `subjectInterfaces` keeps what was",
        " * declared, for a UI that wants to say `party` rather than list members.",
        " */",
        "export const PREDICATES = {",
    ]
    for name, spec in sorted(ontology.predicates.items()):
        objects = "literal" if spec.is_literal else sorted(spec.entity_object_types)
        lines.append(
            f"  {_ts_literal(name)}: {{ subject: {_ts_literal(sorted(spec.subject))}, "
            f"object: {_ts_literal(objects)}, "
            f"allowsLiteral: {'true' if spec.allows_literal else 'false'}, "
            f"category: {_ts_literal(spec.category)}, "
            f"symmetric: {'true' if spec.symmetric else 'false'}, "
            f"identifier: {'true' if spec.identifier else 'false'}, "
            f"subjectInterfaces: {_ts_literal(sorted(spec.subject_interfaces))}, "
            f"objectInterfaces: {_ts_literal(sorted(spec.object_interfaces))}, "
            f"module: {_ts_literal(ontology.owner_module(name))} }},"
        )
    lines += [
        "} as const;",
        "",
        "export type HandlingCode = (typeof HANDLING_CODES)[number];",
        "export type SourceType = (typeof SOURCE_TYPES)[number];",
        "export type ObjectTypeName = keyof typeof OBJECT_TYPES;",
        "export type InterfaceName = keyof typeof INTERFACES;",
        "export type CategoryName = keyof typeof CATEGORIES;",
        "export type PredicateName = keyof typeof PREDICATES;",
        "",
    ]
    return "\n".join(lines)


# ── the entry point ─────────────────────────────────────────────────────────


def plan(
    composition: Composition,
    ontology: Ontology,
    *,
    repo_root: Path,
    release: dict[str, Any] | None = None,
) -> GenerateReport:
    """Everything `aegis ontology generate` would write, without writing it."""
    artifact = composed_artifact(composition, ontology)
    release_path = repo_root / "ontology" / "release.json"
    previous: dict[str, Any] | None = None
    if release_path.exists():
        previous = json.loads(release_path.read_text(encoding="utf-8"))

    return GenerateReport(
        files=[
            GeneratedFile(
                repo_root / "ontology" / "history" / f"composed-{ontology.version}.json",
                canonical_json(artifact),
            ),
            GeneratedFile(
                release_path,
                canonical_json(release_metadata(artifact, release=release, previous=previous)),
            ),
            GeneratedFile(
                repo_root / "ui" / "src" / "api" / "ontology.ts",
                typescript_constants(ontology),
            ),
        ]
    )
